--INCLUSÃO DE DADOS NA TABELA DEPARTAMENTOS  
  INSERT INTO DEPARTAMENTOS
     VALUES('ADM',
	        'ADMINISTRACAO')
  INSERT INTO DEPARTAMENTOS
     VALUES('RH',
	        'RECURSOS HUMANOS')

--INCLUSÃO DE DADOS NA TABELA FUNCIONARIOS
  INSERT INTO FUNCIONARIOS
     VALUES('AA01',
	        'JOSE DA SILVA',
			1210.45,
			'ADM',
			'12/01/2013',
			20,
			'JOSE@YAHOO.COM.BR')
  INSERT INTO FUNCIONARIOS
     VALUES('AA02',
	        'RENATA SA',
			2455.50,
			'ADM',
			'11/11/1995',
			32,
			'RENATA@YAHOO.COM.BR')
  INSERT INTO FUNCIONARIOS
     VALUES('AA03',
	        'MARIA FERNANDA',
			2832.32,
			'RH',
			'02/22/2009',
			28,
			'MARIA@YAHOO.COM.BR')
  INSERT INTO FUNCIONARIOS
     VALUES('AA04',
	        'ANTONIO PEIXOTO',
			832.32,
			'RH',
			'05/05/1999',
			20,
			'TONHO@YAHOO.COM.BR')
--FUNCIONARIO SEM EMAIL
  INSERT INTO FUNCIONARIOS
     (
	     CODFUN,
		 NOMEFUN,
		 SALARIOFUN,
		 DEPTOFUN,
		 ADMISSFUN,
		 IDADEFUN)
     VALUES('AA05',
	        'JOAO SOUZA',
			1234.55,
			'ADM',
			'06/06/2010',
			25)
			
--MOSTRAR TODOS OS DADOS NA TABELA FUNCIONARIOS
  SELECT * FROM FUNCIONARIOS
  
--MOSTRAR O NOME E SALARIO DOS FUNCIONARIOS QUE 
--RECEBEM MAIS DE R$1000,00 E ORDENADO CRESCENTE PELO NOME 
  SELECT NOMEFUN, SALARIOFUN
     FROM FUNCIONARIOS
     WHERE SALARIOFUN > 1000.00
     ORDER BY NOMEFUN

--MOSTRAR O NOME, SALARIO E DATA DE ADMISSÃO DOS FUNCIONARIOS
--CUJA A DATA DE ADMISSÃO FOI ENTRE 01/01/2000 E 31/12/2010
--E ORDENADO CRESCENTE PELO NOME
  SELECT NOMEFUN, SALARIOFUN, ADMISSFUN
     FROM FUNCIONARIOS
     WHERE ADMISSFUN BETWEEN '01/01/2000' AND '12/31/2010'
     ORDER BY NOMEFUN

--MOSTRAR O NOME, SALARIO E IDADE DOS FUNCIONARIOS
--CUJA IDADE É 20 E 22 E ORDENADO CRESCENTE PELO NOME
  SELECT NOMEFUN, SALARIOFUN, IDADEFUN
     FROM FUNCIONARIOS
     WHERE IDADEFUN IN (20,22)
     ORDER BY NOMEFUN
	 
--MOSTRAR NOME E SALARIO DOS FUNCIONARIOS
--CUJO NOME POSSUI A LETRA TABELA E ORDENADO
--DECRESCENTE PELO NOME
  SELECT NOMEFUN, SALARIOFUN
     FROM FUNCIONARIOS
     WHERE NOMEFUN LIKE '%T%'
     ORDER BY NOMEFUN DESC
	
--MOSTRAR AS SOMA DOS SALARIOS DO DEPARTAMENTO DE ADM
  SELECT SUM(SALARIOFUN) AS "SOMA DOS SALARIOS DA ADM"
     FROM FUNCIONARIOS
	 WHERE DEPTOFUN = 'ADM'
	 
--MOSTRAR A SOMA DOS SALARIOS DOS FUNCIONARIOS DE
--CADA DEPARTAMENTO COM AGRUPAMENTO
  SELECT DEPTOFUN, SUM(SALARIOFUN) AS "SOMA DOS SALARIOS"
     FROM FUNCIONARIOS
     GROUP BY DEPTOFUN
	 
--MOSTRAR O NOME, O DEPARTAMENTO E O SALARIO DO FUNCIONARIOS
--CUJO SALARIO É MAIOR R$1000,00 E ORDENADO CRESCENTE PELO NOME
  SELECT A.NOMEFUN, B.NOMEDEPTO, A.SALARIOFUN
     FROM FUNCIONARIOS A, DEPARTAMENTOS B
	 WHERE B.CODDEPTO = A.DEPTOFUN
	       AND SALARIOFUN > 1000.00
     ORDER BY NOMEFUN
	 
--MOSTRAR O NOME E O SALARIO DO FUNCIONARIO DO DEPARTAMENTO ADM
--CUJO O SALARIO TEM QUE SER MAIOR QUE A MEDIA DOS SALARIOS DOS
--FUNCIONARIOS DO DEPARTAMENTO DE RH
  SELECT NOMEFUN, SALARIOFUN
     FROM FUNCIONARIOS
	 WHERE DEPTOFUN = 'ADM'
	       AND SALARIOFUN > (SELECT AVG(SALARIOFUN)
		                        FROM FUNCIONARIOS
								WHERE DEPTOFUN = 'RH ')
     ORDER BY NOMEFUN
	 
--MOSTRAR O NOME E O SALARIO DO FUNCIONARIO DO DEPARTAMENTO ADM
--CUJO O SALARIO TEM QUE SER MAIOR QUE A MEDIA DOS SALARIOS DE
--TODOS OS FUNCIONARIOS DO DEPARTAMENTO DE RH
  SELECT NOMEFUN, SALARIOFUN
     FROM FUNCIONARIOS
	 WHERE DEPTOFUN = 'ADM'
	       AND SALARIOFUN > ALL(SELECT AVG(SALARIOFUN)
		                           FROM FUNCIONARIOS
								   WHERE DEPTOFUN = 'RH ')
     ORDER BY NOMEFUN
	 
--MOSTRAR O NOME E O SALARIO DO FUNCIONARIO DO DEPARTAMENTO ADM
--CUJO O SALARIO TEM QUE SER MAIOR QUE A MEDIA DOS SALARIOS DE
--QUALQUER UM DOS FUNCIONARIOS DO DEPARTAMENTO DE RH
  SELECT NOMEFUN, SALARIOFUN
     FROM FUNCIONARIOS
	 WHERE DEPTOFUN = 'ADM'
	       AND SALARIOFUN > ANY(SELECT AVG(SALARIOFUN)
		                           FROM FUNCIONARIOS
								   WHERE DEPTOFUN = 'RH ')
     ORDER BY NOMEFUN
	 
--MOSTRAR O NOME E O SALARIO DO FUNCIONARIO DO DEPARTAMENTO ADM
--SE EXISTE CUJO O SALARIO MAIOR QUE R$1000 DOS SALARIOS DOS 
--FUNCIONARIOS DO DEPARTAMENTO DE RH
  SELECT NOMEFUN, SALARIOFUN
     FROM FUNCIONARIOS
	 WHERE DEPTOFUN = 'ADM'
	       AND EXISTS(SELECT AVG(SALARIOFUN)
		                 FROM FUNCIONARIOS
						 WHERE DEPTOFUN = 'RH '
						       AND SALARIOFUN > 1000.00)
     ORDER BY NOMEFUN
	 
--ATUALIZAR O SALARIO DO FUNCIONARIO DO CODIGO AA04 PARA R$1000
  UPDATE FUNCIONARIOS
     SET SALARIOFUN = 1000.00
     WHERE CODFUN = 'AA04'

--EXCLUIR FUNCIONARIO DO CODIGO AA04	
  DELETE FROM FUNCIONARIOS
     WHERE CODFUN = 'AA04'  