--CRIACAO DE TABELAS DEPARTAMENTOS E FUNCIONARIOS  
  CREATE TABLE DEPARTAMENTOS
	(CODDEPTO      CHAR(3) PRIMARY KEY NOT NULL,
	 NOME DEPTO    VARCHAR(30)         NOT NULL)

  CREATE TABLE FUNCIONARIOS
    (CODFUN        CHAR(4) PRIMARY KEY NOT NULL,
     NOMEFUN       VARCHAR(30)         NOT NULL,
	 SALARIOFUN    DECIMAL(8,2)        NOT NULL,
	 DEPTOFUN      CHAR(3)             NOT NULL,
	 ADMISSFUN     DATE                NOT NULL,
	 IDADEFUN      SMALLINT            NOT NULL,
	 EMAILFUN      VARCHAR(30))
	 
--CRIACAO DE INDICES ENTRE AS TABELAS 
--DEPARTAMENTOS E FUNCIONARIOS
  CREATE UNIQUE INDEX IDXFUNC
     ON FUNCIONARIOS(CODFUN)
  CREATE UNIQUE INDEX IDXDEPTO
     ON DEPARTAMENTOS(CODDEPTO)

--CRIACAO DE RELACIONAMENTO ENTRE AS TABELAS 
--DEPARTAMENTOS E FUNCIONARIOS
  ALTER TABLE FUNCIONARIOS
     ADD FOREIGN KEY(DEPTOFUN)
	 REFERENCES DEPARTAMENTOS
	 ON DELETE RESTRICT